- name: Setup ZSH
  hosts: all
  tasks:
    - name: Clone .zshrc config to remote
      ansible.builtin.copy:
        src: ../../on-client/.zshrc
        dest: ~/.zshrc

    - name: Change shell to zsh
      ansible.builtin.user:
        name: leo
        shell: /bin/zsh
      become: yes