- name: Docker installation playbook
  hosts: all
  vars_files:
    - secret
  become: yes
  tasks:
    - name: Download the docker .repo file
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'
    
    - name: Import Docker CE GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://download.docker.com/linux/fedora/gpg
        fingerprint: "060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35"

    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
